apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: khkw6rzai-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: khkw6rzai-python 
  name: khkw6rzai-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: khkw6rzai-python 
